name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
<<<<<<< HEAD
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:assignment3
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
=======
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
>>>>>>> buildroot-assignments-base/master
